### ISSUE TITLE
R1 and R2 specs

### ISSUE THREAD

**Issue by zhulik** [Erriez/ESPHomePCPowerControlHomeAssistant#1]
Hello, 

I'm new to electronics but I'd like to build your device. Probably I don't know how to properly use KiCad and find the information in the blueprints, but could you please specify specs or exact models of R1 and R2?

**Comment by Erriez** [comment]
Hi @zhulik, Resistor R1 is 180Ohm 1/4Watt and R2 is 1kOhm 1/4Watt. The package depends on the type you want to solder on the PCB, such as TH (Through Hole) or SMD. You can use any resistor package and is not critical. Success!
