### ISSUE TITLE
Invoke power button without homeassistant (by MQTT / API via Browser)

### ISSUE THREAD

**Issue by backupandforkacc** [Erriez/ESPHomePCPowerControlHomeAssistant#10]
Thank you for this nice project.

Is there a chance to invoke the power button action without a homeassistant installation? 

The easiest would be a dashboard directly on the ESP, another ways would be via the API. I have read some ESP Home documentation, but I am not a programmer and failed so far to find a link to something to invoke by browser. I have limited knowledge about ESP.

**Comment by jojo-Hub** [comment]
Yes, this can be done easily with the [web server component](https://esphome.io/components/web_server.html#web-server-component): just add

`web_server:`

to the .yaml-config file and enter your ESP's IP into a browser in the same network.

Some documentation said that without an HA-connection, the ESP will reset and re-initialize every 15 min (I have not searched how to disable this). But as long as the ESP-init dos not interfere with the pins used to connect to your PC's power and reset line, everything should be fine. Have a look at some documentation: [ESP8266](https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/), [ESP32](https://randomnerdtutorials.com/esp32-pinout-reference-gpios/). 

BTW: You can even make a [remote control](https://community.home-assistant.io/t/esphome-to-esphome-direct-communication/101370/7) with a button attached to a second ESP-board. This also works without a running HA-server.

**Comment by Erriez** [comment]
@backupandforkacc and @jojo-Hub Thanks for your details. I was not aware of the ESP webserver component and is useful for other projects as well. I'll close this issue as the original question is answered.
