### ISSUE TITLE
PIN14 always returns "1"

### ISSUE THREAD

**Issue by pixelwave** [Erriez/ESPHomePCPowerControlHomeAssistant#11]
I tried to replicate your project, so far power on works. But somehow my PIN32 (reads RESET pin from mainboard) always returns "1" no matter if power button pressed and pc running or not. I only shows "0" when I unplug the mainboard completely?

![IMG_1793](https://github.com/Erriez/ESPHomePCPowerControlHomeAssistant/assets/19491804/0f7785f3-f4cb-4773-bcd4-ee94524301a2)

![IMG_1796](https://github.com/Erriez/ESPHomePCPowerControlHomeAssistant/assets/19491804/888cfb88-b3f5-4310-a799-fa9858fe88ca)

My ESP32 test code:

```
import machine
import time

# Define the pin for the LED and the boot button
led_pin = machine.Pin(2, machine.Pin.OUT)
button_pin = machine.Pin(0, machine.Pin.IN)
power_pin = machine.Pin(13, machine.Pin.OUT)
reset_pin = machine.Pin(32, machine.Pin.IN)

# Function to turn on the LED
def turn_on_led(pin):
    pin.on()

# Function to turn off the LED
def turn_off_led(pin):
    pin.off()

# Main loop
while True:
    if button_pin.value() == 0:
        turn_on_led(led_pin)
        power_pin.on()
    else:
        turn_off_led(led_pin)
        power_pin.off()

    print("Power State:", reset_pin.value())


```

**Comment by pixelwave** [comment]
I figured out ... what works though ... if I connect PIN32 to POWER_LED+ on the ATX header. Is that safe to do?

![IMG_1797](https://github.com/Erriez/ESPHomePCPowerControlHomeAssistant/assets/19491804/85195bb0-b412-4fe7-9dd9-39614f8678c3)

![IMG_1798](https://github.com/Erriez/ESPHomePCPowerControlHomeAssistant/assets/19491804/aea36418-efe0-4ba7-a51b-1108cded26ad)

**Comment by Erriez** [comment]
@pixelwave Thanks for using this project. Reading the computer power state is motherboard dependent. What works for you may not work on another motherboard as it is not standardized. When the reset pin does not work, I also recommend to use a different pin like the power LED. When the input pin of the ESP32 does not exceed 3.3V, then you can use this pin. Otherwise you can use an optocoupler for isolation. Success!

**Comment by pixelwave** [comment]
Thanks for the reply! Yes I was quite confused that it works in your case. After my research usually the feedback was:

`The reset pin on a PC motherboard is typically used to perform a hardware reset of the computer, forcing it to restart. It is not designed to provide information about the power state of the PC. The reset pin is a momentary contact switch or signal that, when triggered, causes the computer to reset and begin the boot process.`

I went exactly down the road that you suggested in the meantime. With the help of the reddit community I came up with this scheme using optocouplers and the power LED. I assembled it - and it works! 

<img width="1024" alt="Screenshot 2023-10-23 at 08 19 23" src="https://github.com/Erriez/ESPHomePCPowerControlHomeAssistant/assets/19491804/c2e93c09-d9c5-4938-a043-cc23cbded394">

This code I used for testing:
```
import machine
import time

# Define boot button on ESP32
button_pin = machine.Pin(0, machine.Pin.IN)
power_pin = machine.Pin(13, machine.Pin.OUT)
reset_pin = machine.Pin(14, machine.Pin.IN)
reset_pin.init(mode=machine.Pin.IN, pull=machine.Pin.PULL_UP)

# Main loop
while True:
    if button_pin.value() == 0:
        power_pin.on()
    else:
        power_pin.off()

    print("Power State:", reset_pin.value())
```

With the onboard button of an ESP32 dev board (pin0) I can trigger the pc boot (pin13). When the PC is running pin14 outputs low/0 when it is off high/1. I tried to use PULL_DOWN on pin14 to reverse that but the output was always 0/low then.

Btw .. do you have a tip for a good online forum / community where ESP32/electronics stuff like this can be discussed?

**Comment by Erriez** [comment]
Good to hear that you found a solution. I probably designed exactly this schematic when opto isolation is required. So well done. :-)

> Btw .. do you have a tip for a good online forum / community where ESP32/electronics stuff like this can be discussed?

I recommend https://hardwarerecs.stackexchange.com which if pretty new / Stackoverflow or Reddit.

I assume this issue can be closed. Otherwise let me know.
