### ISSUE TITLE
Parts list

### ISSUE THREAD

**Issue by That-Dude** [Erriez/ESPHomePCPowerControlHomeAssistant#2]
Cool project! I would like to build this but I'm struggling with the value of resistor R1 on your schematic 1B0E ?

**Comment by Erriez** [comment]
@That-Dude Thanks for your feedback! Resistor R1 is 180Ohm. Sorry, it is a typo. For more information, please refer to https://github.com/Erriez/ESPHomePCPowerControlHomeAssistant/issues/1
