### ISSUE TITLE
Typing error in circuit

### ISSUE THREAD

**Issue by jnsw** [Erriez/ESPHomePCPowerControlHomeAssistant#4]
https://github.com/Erriez/ESPHomePCPowerControlHomeAssistant/blob/master/README.md

```
[...]
Pin D1 is used to read the power status from the reset pin: High is on, Low is off. Transistor Q1 is used for secure isolation between ESP8266 and motherboard.

Pin D2 is used to pull the power button low to generate a short or long press. Resistor R1 is used to minimize current when the IO pin is accidentally set to output.
[...]
```

it's written different than on the picture, which description is correct? the image or the text?

**Comment by Erriez** [comment]
Hi @jnsw, Thanks for your feedback. The schematic and text in the `README.md` matches as follows:

![image](https://user-images.githubusercontent.com/8849873/189475523-ac48c30b-9334-430d-a189-d062aeefb1a7.png)

* Pin `D1` is the power status (monitor) ESP input pin: It is used to monitor the motherboard power state. Arrow `<- IN` below the `R1`.
* Pin `D2` is an ESP output pin to control the power button. Arrow `OUT ->` below `R2`.

Does this answer your question?
