### ISSUE TITLE
Reset pin

### ISSUE THREAD

**Issue by nvtkaszpir** [Erriez/ESPHomePCPowerControlHomeAssistant#5]
Question:
Usually motherboard J2 header has pins which are used to turn on leds to show on the computer case that the computer is on.

Why not use that for pc power status, and use reset button in similar way as power button is used (this way allowing computer reset without forced powering down)?

**Comment by Erriez** [comment]
@nvtkaszpir Thanks for your feedback. You're right, the power LED can be used as well to detect the power state. I started with a motherboard where this LED was not available and designed 2 IO pins. If you have sufficient ESP8266 or ESP32 IO pins available, you can for example configure:
- 1 output pin for power button
- 1 output pin for reset button
- 1 input pin to read the power state from the LED
So it is flexible and a starting point for your needs.

**Comment by nvtkaszpir** [comment]
Ah ok, now it's more clear what were limitations of the design.
Thanks!
