### ISSUE TITLE
Reset button always is 5v

### ISSUE THREAD

**Issue by GrzesiuS** [Erriez/ESPHomePCPowerControlHomeAssistant#7]
Hello,

I followed all instructions and can turn on/off my PC but detection from the reset pin is impossible because it's always in the high state even if the PC is disabled. I plan to use reset GND to detect low state.

Do you think it's a good idea?

**Comment by Erriez** [comment]
Yes, you can try other pins as well as it is motherboard specific. Succes!

**Comment by GrzesiuS** [comment]
I tried the power LED but the behavior is the same :|

**Comment by Erriez** [comment]
Is the LED pin 3V3? Can you check the wiring, for example by pulling the ESP input pin high/low manually to see if this works?

**Comment by GrzesiuS** [comment]
it's 5V bo I got another idea. I use 3.3V from power supply (orange cable) :)

**Comment by Erriez** [comment]
Sounds good. Please notice that the ESP8266/ESP32 pins are 3V3 tolerant. It may work with 5V input, but is beyond the absolute maximum ratings and may damage input pins. Success!
